export enum Steps {
  AWAITING_NAME = 'AWAITING_NAME',
  AWAITING_CAPTURE = 'AWAITING_CAPTURE',
  AWAITING_CONFIRMATION = 'AWAITING_CONFIRMATION',
  AWAITING_MANUAL_INPUT = 'AWAITING_MANUAL_INPUT',
  AWAITING_FLOW_INTERACTION = 'AWAITING_FLOW_INTERACTION',
  AWAITING_DOC_INFO_MANUAL = 'AWAITING_DOC_INFO_MANUAL',
  AWAITING_INVOICE_SELECTION_MANUAL = 'AWAITING_INVOICE_SELECTION_MANUAL',
  AWAITING_PAYMENT_METHOD_MANUAL = 'AWAITING_PAYMENT_METHOD_MANUAL',
  PROCESSING_PAYMENT = 'PROCESSING_PAYMENT',
}
