services:
  db:
    image: postgres:latest
    restart: always
    # set shared memory limit when using docker-compose
    shm_size: 128mb
    volumes:
      - db_data_sirca:/var/lib/postgresql/data
    environment:
      POSTGRES_PASSWORD: 123456d
      POSTGRES_USER: postgres
      POSTGRES_DB: sirca
    ports:
      - '5433:5432'
  redis:
    image: redis:7.2-alpine
    restart: always
    command: redis-server --requirepass 123456d
    ports:
      - '6379:6379'
    volumes:
      - redis_data:/data

volumes:
  db_data_sirca:
  redis_data:
