export enum ErrorCode {
  // General & Validation
  INTERNAL_SERVER_ERROR = 'INTERNAL_SERVER_ERROR',
  INVALID_INPUT = 'INVALID_INPUT',
  MISSING_REQUIRED_FIELD = 'MISSING_REQUIRED_FIELD',
  UNAUTHORIZED = 'UNAUTHORIZED',
  FORBIDDEN = 'FORBIDDEN',
  RESOURCE_NOT_FOUND = 'RESOURCE_NOT_FOUND',
  DUPLICATE_RESOURCE = 'DUPLICATE_RESOURCE',
  FOREIGN_KEY_VIOLATION = 'FOREIGN_KEY_VIOLATION',

  // Domain Business Rules
  INVALID_DOMAIN_OPERATION = 'INVALID_DOMAIN_OPERATION',
  CONTRACT_INACTIVE = 'CONTRACT_INACTIVE',
  CONTRACT_NOT_FOUND = 'CONTRACT_NOT_FOUND',
  PAYMENT_ALREADY_APPROVED = 'PAYMENT_ALREADY_APPROVED',
  PAYMENT_INVALID_AMOUNT = 'PAYMENT_INVALID_AMOUNT',

  // External Services
  EXTERNAL_SERVICE_ERROR = 'EXTERNAL_SERVICE_ERROR',
  AWS_S3_ERROR = 'AWS_S3_ERROR',
  AWS_SES_ERROR = 'AWS_SES_ERROR',
  OCR_PROCESSING_ERROR = 'OCR_PROCESSING_ERROR',
}
